### PR TITLE
Use ArrayPool.Shared for StreamCopyOperation

### LINKED ISSUE #91: [Perf] Pool StreamCopyOperation buffers
This 16kb buffer causes lots of GCs. https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/StreamCopyOperation.cs#L20

Also, does it need to be 16kb?

### PR DESCRIPTION
**Pull request by benaadams**
Resolves  #91

### CODE REVIEW

**Comment by davidfowl** [comment]
Also see https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Extensions/StreamCopyOperation.cs

We should unify these classes.

**Comment by benaadams** [comment]
Dangers of `internal` ;-)

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/issues/528

**Comment by Tratcher** [comment]
Rebased and merged. @DamianEdwards

**Pull request closed without merging**
