### PR TITLE
Add ServiceCollection extension overload accepting options

### PR DESCRIPTION
**Pull request by kichalla**
@Eilon

### CODE REVIEW

**Comment by Tratcher** [comment]
:-1: This doesn't make sense to do for directory browser when none of the other middleware in this repo can be configured this way.

**Comment by kichalla** [comment]
@Tratcher The idea of this change was to provide an overload to configure options if there is an extension on `IServiceCollection`. That said this was the only middleware having an extension...so should this be deleted entirely?

**Comment by Tratcher** [comment]
This is the only middleware that requires services. Don't remove it.

**Comment by Eilon** [comment]
Hmm I talked to @Tratcher and this might indeed be a case where it doesn't make as much sense to have this overload. I don't think it's super wrong, but perhaps not too useful, and might even reduce the usability of the API. In the case of directory browser it turns out you should call https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/DirectoryBrowserExtensions.cs#L56 to set the options.

**Comment by kichalla** [comment]
:up: :date:

**Comment by Eilon** [comment]
:shipit:

**Comment by kichalla** [comment]
f202f5b7b3a4763f212722c79aaf4945f2a3c676

**Pull request closed without merging**
