### PR TITLE
Use dynamic ports in StaticFileMiddlewareTests

### PR DESCRIPTION
**Pull request by mikeharder**
- Replace hardcoded port "12345" with dynamic ports to improve test reliability
- Addresses https://github.com/aspnet/Home/issues/3063
- Depends on https://github.com/aspnet/Hosting/pull/1387

### CODE REVIEW

**Comment by mikeharder** [comment]
Alternatively, we could add a new public method `BuildTestUri(ServerType serverType)` to https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/TestUriHelper.cs, then use this method instead of the private `GetTestUrl()`.  It will be a little more work since it's a new cross-repo API, but it avoids some duplicate code.

**Comment by mikeharder** [comment]
Even though the methods are public, it turns out no other repos currently use either `BuildTestUri()` or `GetNextPort()` from IntegrationTesting (Kestrel has its own copy of `GetNextPort()`:

https://github.com/search?l=C%23&q=org%3Aaspnet+buildtesturi&type=Code
https://github.com/search?l=C%23&q=org%3Aaspnet+getnextport&type=Code

So I'm not sure if we want to start the precedent of directly calling either `BuildTestUri()` or `GetNextPort()`.  We may instead want to make them private in IntegrationTesting.

**Comment by mikeharder** [comment]
@anurse: Any thoughts regarding whether it's better to share common code like `BuildTestUri()` and `GetNextPort()` in integration testing, or just copying the code to repos which need it?  It's fairly short and simple code, so I'm not sure if the cross-repo dependency is worth it.

**Comment by Tratcher** [comment]
Having a dependency for BuildTestUri seems fine, the logic keeps getting more complicated and we only want to maintain it in one place.

**Comment by anurse** [comment]
For repos that already have the dependency sure, I'm not sure it's worth adding new cross-repo dependencies.

**Comment by mikeharder** [comment]
Ok, I will move the logic to IntegrationTesting and update this PR tomorrow.

**Comment by mikeharder** [comment]
Updated to use new helper methods added in https://github.com/aspnet/Hosting/pull/1387.

**Pull request merged**
