### PR TITLE
React to wwwroot hosting changes

### PR DESCRIPTION
**Pull request by pakrym**
Reacts to https://github.com/aspnet/Hosting/pull/493
Now server does not automatically falls back to `approot` as `webroot`. So `webroot` needs to be specified explicitly

@JunTaoLuo @BrennanConroy @Tratcher @victorhurdugaci

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Can you please explain in PRs what was actually broken?

**Comment by pakrym** [comment]
@victorhurdugaci  done

**Comment by BrennanConroy** [comment]
Looks good

**Comment by victorhurdugaci** [comment]
Yeah, looks good. :shipit: when the CI verification passes

**Comment by pakrym** [comment]
@davidfowl will add one, it throws exception from `MapPath` method.

**Comment by pakrym** [comment]
@davidfowl It doesn't trow by default, just 404 everything. Only `MapPath` method throws because it uses `WebRootPath` directly. Want a test for it?

**Comment by davidfowl** [comment]
Yep

**Comment by pakrym** [comment]
@davidfowl https://github.com/aspnet/Hosting/pull/505/files

**Pull request merged**
