### PR TITLE
14.28 If-Unmodified-Since - Incorrect condition

### PR DESCRIPTION
**Pull request by joostvanhassel**
14.28 If-Unmodified-Since had a condition on ifModifiedSince, which could be undefined. Should be ifUnmodifiedSince

### CODE REVIEW

**Comment by Tratcher** [comment]
That's a concerning typo. Are there any tests that cover IfUnmodifiedSince?

**Comment by joostvanhassel** [comment]
No, unfortunately not.

Also, I'm wondering if the header should even be taken in consideration in case the If-Modified-Since header is also defined; this would:
a) not make sense
b) not comply with this line from spec in case If-Modified-Since results in a 304: 

> If the request normally (i.e., without the If-Unmodified-Since header) would result in anything other than a 2xx status, the If- Unmodified-Since header should be ignored.

But maybe this should be logged in a seperate bug (please advise).

**Comment by Tratcher** [comment]
Try to add a test please.

**Comment by Tratcher** [comment]
As for If-Modified-Since vs If-Unmodified-Since, no, it does not make much sense to provide both, but if the client does that then I'm not too concerned if they get a strange response.

**Comment by Tratcher** [comment]
FYI: This is a regression introduced by https://github.com/aspnet/StaticFiles/commit/3a0d8c43ca1cbfb96def9c2885418f96702e42d1#diff-fdacd70ec71d4cfc5d8436b604e52355R212 @pakrym

**Comment by pakrym** [comment]
Thank you, you commit was merged as part of https://github.com/aspnet/StaticFiles/pull/145

**Comment by joostvanhassel** [comment]
@pakrym I just started working on some unittests when I noticed you are doing the same. Much appreciated.

**Pull request closed without merging**
