### PR TITLE
text/javascript is now the "correct" mime type

### PR DESCRIPTION
**Pull request by RehanSaeed**
I noticed this change when I got a warning while trying out [Sonar](https://github.com/sonarwhal/sonar/issues/568). Apparently the standards bodies have changed their minds:

- https://github.com/whatwg/html/pull/3096
- https://github.com/bmeck/I-D/issues/2

### CODE REVIEW

**Comment by Tratcher** [comment]
@muratg Triage: does this constitute a breaking change for clients?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2441

**Comment by aspnet-hello** [comment]
Sorry I was a bad bot. Re-opening this PR.

**Comment by muratg** [comment]
@glennc Thoughts on this one?

**Comment by Eilon** [comment]
@glennc / @Tratcher / @muratg - any further action planned on this PR?

**Comment by muratg** [comment]
We’re closing this PR because we don’t feel that this change is a good fit for the product at this time. Please file a bug to be considered in 3.0.0 for types you'd like 

We thank you for the contribution and look forward to collaborating more in the future.

**Comment by RehanSaeed** [comment]
Bug raised at https://github.com/aspnet/AspNetCore/issues/3614

**Pull request closed without merging**
