### PR TITLE
Some minor cleanups

### PR DESCRIPTION
**Pull request by SimonCropp**
Feel free to cherry pick any. or let me know if u want isolated PRs for any of them

### CODE REVIEW

**Comment by SimonCropp** [comment]
thoughts on suppressing CS1573?

if we r just going to have dozens of `/// <param name="app"></param>`, we r essentially ignoring it anyway

```
/Users/travis/build/aspnet/StaticFiles/src/Microsoft.AspNetCore.StaticFiles/StaticFileExtensions.cs(33,83): 
error CS1573: Parameter 'app' has no matching param tag in the XML comment for 'StaticFileExtensions.UseStaticFiles(IApplicationBuilder, string)' (but other parameters do) [/Users/travis/build/aspnet/StaticFiles/src/Microsoft.AspNetCore.StaticFiles/Microsoft.AspNetCore.StaticFiles.csproj]
```

**Comment by Tratcher** [comment]
We'd rather fill it in with something simple than suppress the warning.

**Comment by Tratcher** [comment]
FYI: we're currently developing in the release/2.2 branch.

**Comment by SimonCropp** [comment]
ok i will submit a new PR targeting 2.2

**Pull request closed without merging**
