### PR TITLE
Use UTC

### PR DESCRIPTION
**Pull request by BrennanConroy**
#66 
@Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
Verify UTC in a test? https://github.com/aspnet/StaticFiles/blob/dev/test/Microsoft.AspNet.StaticFiles.Tests/CacheHeaderTests.cs#L140

**Comment by Tratcher** [comment]
And test IfModifiedSince with non-UTC https://github.com/aspnet/StaticFiles/blob/dev/test/Microsoft.AspNet.StaticFiles.Tests/CacheHeaderTests.cs#L247

**Comment by BrennanConroy** [comment]
:up: :date:

**Comment by Tratcher** [comment]
:shipit:

**Pull request merged**
