### PR TITLE
Add application/manifest+json ( .webmanifest)

### PR DESCRIPTION
**Pull request by RehanSaeed**
Added support fot the `.webmanifest` file extension which returns `application/manifest+json`.

See [sonarwhal documentation](https://sonarwhal.com/docs/user-guide/rules/manifest-file-extension/) and [W3C](https://w3c.github.io/manifest/#media-type-registration) for reference.

### CODE REVIEW

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2440

**Comment by aspnet-hello** [comment]
Sorry I was a bad bot. Re-opening this PR.

**Comment by rickyruiz** [comment]
Any news on when is this PR going live? 

___

If anyone is stuck with this, you can create a custom content type provider like so:

```
  public class PwaContentTypeProvider : FileExtensionContentTypeProvider
  {
    public PwaContentTypeProvider()
    {
      Mappings.Add(".webmanifest", "application/manifest+json");
    }
  }
```

In Startup.cs:

``` 
app.UseStaticFiles(new StaticFileOptions()
{
  ContentTypeProvider = new PwaContentTypeProvider()
});
```

**Comment by Tratcher** [comment]
@glennc @muratg

**Comment by muratg** [comment]
We’re closing this PR because we don’t feel that this change is a good fit for the product at this time. Please file a bug to be considered in 3.0.0 for types you'd like 

We thank you for the contribution and look forward to collaborating more in the future.

**Comment by RehanSaeed** [comment]
@muratg Any reason not to include this official [W3C](https://w3c.github.io/manifest/#media-type-registration) web standard MIME type? It's a change that has very little impact and is clearly scoped.

**Comment by RehanSaeed** [comment]
Bug raised at https://github.com/aspnet/AspNetCore/issues/3613

**Pull request closed without merging**
