### PR TITLE
Added MIME Types

### PR DESCRIPTION
**Pull request by RehanSaeed**
Added the following MIME types which I have found to be missing:

.json - application/json (This one is pretty unbelievable)
.ttc - application/x-font-ttf
.webp - image/webp
.appcache - text/cache-manifest
.manifest - text/cache-manifest

Also the following MIME types need updating:

.ttf should be application/x-font-ttf and not application/octet-stream

### CODE REVIEW

**Comment by Tratcher** [comment]
What are your references for these definitions?

**Comment by RehanSaeed** [comment]
- [.json - application/json](http://www.iana.org/assignments/media-types/media-types.xhtml)
- [.appcache - text/cache-manifest](http://www.iana.org/assignments/media-types/text/cache-manifest) and [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache)
- [.manifest - text/cache-manifest](http://www.iana.org/assignments/media-types/text/cache-manifest) and [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache)

There is no official standard MIME type for ttf, ttc and webp.

- .ttf is already included in the list but as application/octet-stream. However this causes a common warning to show in Chrome. See [StackOverflow](http://stackoverflow.com/questions/4051826/font-face-with-wrong-mime-type-in-chrome) and [Google Chrome](https://code.google.com/p/chromium/issues/detail?id=248712). The solution is to use application/x-font-ttf where the x- signifies that this is non-standard. Some people use application/font-ttf instead however.
- ttc is a true type font collection. Unfortunately I can't find an authoritative source for ttf and ttc but [HTML 5 Boilerplate](https://github.com/h5bp/html5-boilerplate/blob/85d79ed6cc33eb7ba5e156085049758f07b47fd9/dist/.htaccess) has both listed as application/x-font-ttf.
- [.webp - image/webp](https://developers.google.com/speed/webp/faq) and [HTML 5 Boilerplate](https://github.com/h5bp/html5-boilerplate/blob/85d79ed6cc33eb7ba5e156085049758f07b47fd9/dist/.htaccess). The first link is the official Google docs.

**Comment by Tratcher** [comment]
@blowdart do you care about any of these?

**Comment by blowdart** [comment]
Nope, you can merge at will.

**Pull request merged**
