### PR TITLE
Use HttpAbstractions StreamCopy

### PR DESCRIPTION
**Pull request by BrennanConroy**
Part 2 of https://github.com/aspnet/HttpAbstractions/issues/528
@Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
:shipit:

**Comment by davidfowl** [comment]
Wait for coherence?

**Comment by BrennanConroy** [comment]
I could, but why for?

**Comment by davidfowl** [comment]
@BrennanConroy mere mortals trying to build, reduce our breakages. It should be quick anyways. We should optimize for not breaking our repos. There's no need to rush this in, coherence should pass very quickly.

**Comment by BrennanConroy** [comment]
Should I push part 1 though?

**Comment by Tratcher** [comment]
Yes

**Pull request merged**
